src/Entity/DoctorInfo.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DoctorInfoRepository")
 */
class DoctorInfo
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", inversedBy="doctorInfo", cascade={"persist", "remove"})
     */
    private $doctor;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $education;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\Type("int")
     */
    private $experience;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $achievements;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $scientific_works;

    /**
     * @ORM\Column(type="string", length=512)
     */
    private $medical_institution;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDoctor(): ?User
    {
        return $this->doctor;
    }

    public function setDoctor(?User $doctor): self
    {
        $this->doctor = $doctor;

        return $this;
    }

    public function getEducation(): ?string
    {
        return $this->education;
    }

    public function setEducation(string $education): self
    {
        $this->education = $education;

        return $this;
    }

    public function getExperience(): ?int
    {
        return $this->experience;
    }

    public function setExperience(int $experience): self
    {
        $this->experience = $experience;

        return $this;
    }

    public function getAchievements(): ?string
    {
        return $this->achievements;
    }

    public function setAchievements(?string $achievements): self
    {
        $this->achievements = $achievements;

        return $this;
    }

    public function getScientificWorks(): ?string
    {
        return $this->scientific_works;
    }

    public function setScientificWorks(?string $scientific_works): self
    {
        $this->scientific_works = $scientific_works;

        return $this;
    }

    public function getMedicalInstitution(): ?string
    {
        return $this->medical_institution;
    }

    public function setMedicalInstitution(string $medical_institution): self
    {
        $this->medical_institution = $medical_institution;

        return $this;
    }
}

src/Controller/DoctorController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Utils\DoctorService;
use App\Utils\UserService;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class DoctorController
 * @package App\Controller
 */
class DoctorController extends AbstractController
{
    /**
     * @var DoctorService
     */
    private $userService;

    /**
     * @var PaginatorInterface
     */
    private $paginator;

    public function __construct(UserService $userService, PaginatorInterface $paginator)
    {
        $this->userService = $userService;
        $this->paginator = $paginator;
    }

    /**
     * @Route("/doctors", name="doctors")
     *
     * @param Request $request
     *
     * @return Response
     */
    public function showAll(Request $request)
    {
        $doctors = $this->paginator->paginate(
            $this->userService->getDoctors(),
            $request->query->getInt('page', 1),
            10
        );

        $pageInfo = [
            'doctors'   => $doctors,
            'title'     => 'Реестр анастезиологов',
        ];

        return $this->render('doctors/index.html.twig', $pageInfo);
    }


    /**
     * @Route("/doctors/{doctorId}", name="doctor")
     * @ParamConverter("doctor", class="App\Entity\User", options={"mapping": {"doctorId": "id"}})
     *
     * @param User $doctor
     * @return Response
     */
    public function showOne(User $doctor) {
        $pageInfo = [
            'title'     => $doctor->getDotsName(),
            'doctor'    => $doctor,
        ];

        return $this->render('doctors/doctor/index.html.twig', $pageInfo);
    }
}

templates/doctors/doctor.html.twig
<div class="card border-0 col-md-5 mt-2 mb-3">
    <div class="card-body border-darkblue rounded-top">
        <div class="row">
            <div class="col-md-4 text-center">
                <img width="150" height="150" class="mb-2" src="/img/user/{{ doctor.image }}"/>
            </div>
            <div class="col-md-8">
                <div class="card-block">
                    <h3 class="card-title text-darkblue">{{ doctor.getFullName }}</h3>
                    <div class="card-body p-0 pt-3">
                        <div class="city">
                            <i class="fas fa-home"></i>&nbsp;<span>Город:&nbsp;{{ doctor.city }}</span>
                        </div>
                        <div class="experience">
                            <i class="fas fa-sort-amount-up"></i>&nbsp;<span>Стаж:&nbsp;{{ doctor.doctorInfo.experience }} лет/года</span>
                        </div>
                        <div class="medical-institution">
                            <i class="fas fa-briefcase"></i>&nbsp;<span>Место работы:&nbsp;{{ doctor.doctorInfo.medicalInstitution }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card-footer border-darkblue bg-darkblue">
        <a
                class="float-right text-white"
                style="text-decoration: none;"
                href="{{ path('doctor', {'doctorId': doctor.id}) }}"
        ><i class="fas fa-angle-right"></i>&nbsp;Подробнее</a>
    </div>
</div>

templates/doctors/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% include 'common/card-wrapper.html.twig' %}

    <div class="row col-md-10 offset-md-1 justify-content-around">
        {% if doctors|length == 0 %}
            {% include 'common/empty-list.html.twig' %}
        {% else %}
            {% for doctor in doctors %}
                {% include 'doctors/doctor.html.twig' with {'doctor': doctor} %}
            {% endfor %}
        {% endif %}
    </div>


    {% include 'common/replacement/pagination.html.twig' with {'items': doctors} %}
{% endblock %}